// src/components/live/DemoCheck.svelte
<script>
    import { onMount } from "svelte";
    let innerWidth = 0;

    onMount(() => {
        innerWidth = window.innerWidth;

        window.addEventListener("resize", () => {
            innerWidth = window.innerWidth;
        });
    });
</script>

{#if innerWidth > 768 }
<slot/>
{:else}
<p>Sorry, this is best viewed on larger screens</p>
{/if}

// src/components/live/DemoCheck.vue
<template>
  <slot v-if="innerWidth > 768" />
  <p v-else>Sorry, this is best viewed on larger screens</p>
</template>

<script setup>
import { ref, onMounted } from 'vue';

const innerWidth = ref(0);

onMounted(() => {
  innerWidth.value = window.innerWidth;

  window.addEventListener('resize', () => {
    innerWidth.value = window.innerWidth;
  });
});
</script>
